# Generated by Django 5.0.6 on 2024-06-11 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='product_name',
        ),
    ]
